In [2]:
import numpy as np

In [3]:
x_init = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_init = np.array([460, 232, 178])
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
b_init = 785.1811367994083

In [5]:
def ComputeCost(x,y,w,b):
    m = x.shape[0]
    PredictedValues = model1(x,y,w,b)
    SumOfCost = 0
    totalCost = 0
    for i in range(m):
        SumOfCost += (PredictedValues[i] - y[i]) **2
    
    totalCost = SumOfCost / (2*m)
    return totalCost

In [6]:
ComputeCost(x_init,y_init,w_init,b_init)

1.5578904330213735e-12

In [38]:
def ComputeGradient(x,y,w,b):
    m = x.shape[0]
    n = x.shape[1]
    dj_dw = np.zeros((n,))
    dj_db = 0.
    for i in range(m):
        predicted = np.dot(x[i],w) + b
        err = predicted - y[i]
        for j in range(n):
            print(dj_dw)
            dj_dw[j] += err * x[i,j]
            print(i,j)
            print(x[i,j])
            
        dj_db += err
        
    dj_db = dj_db / m
    dj_dw = dj_dw / m
    
    return dj_db, dj_dw

In [39]:
ComputeGradient(x_init,y_init,w_init,b_init)

[0. 0. 0. 0.]
0 0
2104
[-0.00500877  0.          0.          0.        ]
0 1
5
[-5.00876517e-03 -1.19029590e-05  0.00000000e+00  0.00000000e+00]
0 2
1
[-5.00876517e-03 -1.19029590e-05 -2.38059181e-06  0.00000000e+00]
0 3
45
[-5.00876517e-03 -1.19029590e-05 -2.38059181e-06 -1.07126631e-04]
1 0
1416
[-7.31768313e-03 -1.19029590e-05 -2.38059181e-06 -1.07126631e-04]
1 1
3
[-7.31768313e-03 -1.67947344e-05 -2.38059181e-06 -1.07126631e-04]
1 2
2
[-7.31768313e-03 -1.67947344e-05 -5.64177537e-06 -1.07126631e-04]
1 3
40
[-7.31768313e-03 -1.67947344e-05 -5.64177537e-06 -1.72350303e-04]
2 0
852
[-8.17870730e-03 -1.67947344e-05 -5.64177537e-06 -1.72350303e-04]
2 1
2
[-8.17870730e-03 -1.88159179e-05 -5.64177537e-06 -1.72350303e-04]
2 2
1
[-8.17870730e-03 -1.88159179e-05 -6.65236712e-06 -1.72350303e-04]
2 3
35


(-1.6739251122999121e-06,
 array([-2.72623577e-03, -6.27197263e-06, -2.21745571e-06, -6.92403379e-05]))

In [ ]:
def gradientDescent(x,y,w,b,ComputeGradient,ComputeCost,alpha):
    for i in range(len(w)):
        w[i] = w[i] - alpha* ComputeGradient()

In [16]:
print(np.zeros((4,)))

[0. 0. 0. 0.]


In [18]:
x = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
x

array([[2104,    5,    1,   45],
       [1416,    3,    2,   40],
       [ 852,    2,    1,   35]])

In [19]:
for i in range(4):
    print(x[0,i])

2104
5
1
45


In [25]:
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
b_init = 785.1811367994083
y_init = np.array([460, 232, 178])
err = (np.dot(x[0],w_init) + b_init) - y_init[0]
value = 0
for i in range(4):
    value += err * x[0,i]
print(value)

-0.0051301753484267465
