In [2]:
import numpy as np

In [3]:
x_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [4]:
print(x_train)
print(y_train)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
[460 232 178]


In [19]:
b_init = 785.1811367994083
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])

In [20]:
def predictSingle(x,w,b):
    n = x.shape[0]
    v = 0
    for i in range(n):
        v+= x[i] * w[i]
        
    v += b
    return v

In [30]:
x_1 = x_train[0, :]
w = w_init
b = b_init
predictSingle(x_1,w,b)

459.9999976194083

In [22]:
def predictVector(x,w,b):
    v = np.dot(x,w) + b
    return v

In [23]:
predictVector(x_1,w,b)

459.9999976194082

In [24]:
def ComputeCost(x,y,w,b):
    m = x.shape[0]
    sqError = 0.0
    for i in range(m):
        error = (np.dot(x[i],w) + b) - y[i]
        sqError += error ** 2
    
    cost = sqError / (2*m)
    return cost
        

In [25]:
ComputeCost(x_train,y_train,w_init,b_init)

1.5578904330213735e-12

In [26]:
def derivative()


SyntaxError: expected ':' (221589408.py, line 1)

In [27]:
m = x_train.shape[0]  # will give number of rows in a matrix
for i in range(m):
    pass


In [31]:
print(x_train[0])
print(w)

[2104    5    1   45]
[  0.39133535  18.75376741 -53.36032453 -26.42131618]
