In [3]:
import numpy as np

In [4]:
x_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [5]:
print(x_train)
print(y_train)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
[460 232 178]


In [6]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])

In [7]:
def predictSingle(x,w,b):
    n = x.shape[0]
    v = 0
    for i in range(n):
        v+= x[i] * w[i]
        
    v += b
    return v

In [8]:
x_1 = x_train[0, :]
w = w_init
b = b_init
predictSingle(x_1,w,b)

459.9999976194083

In [9]:
def predictVector(x,w,b):
    v = np.dot(x,w) + b
    return v

In [10]:
predictVector(x_1,w,b)

459.9999976194082

In [15]:
def ComputeCost(x,y,w,b):
    m = x.shape[0]
    sqError = 0.0
    for i in range(m):
        error = (np.dot(x[i],w) + b) - y[i]
        sqError += error ** 2
    
    cost = sqError / (2*m)
    return cost
        

In [16]:
ComputeCost(x_train,y_train,w_init,b_init)

1.5578904330213735e-12

In [ ]:
def derivative()